### ISSUE TITLE
Hover over global rating for detailed value

### ISSUE THREAD

**Issue by evertvp** [tvgdb/pianissimo#19]

**Comment by tvgdb** [comment]
Detailed value?

**Comment by evertvp** [comment]
The average of all scores.

**Comment by tvgdb** [comment]
The global rating is always the average of all given ratings.

**Comment by evertvp** [comment]
Wel yeah, but if one person gives a score of 4 and another a score of 4.5 it will display a score of 4. The actual average is 4.25, which is what should be displayed when hovering.

**Comment by tvgdb** [comment]
Ratings are rounded to the nearest 0.5, and if that's not possible (ex. 4.25), they are rounded down. This is fixed and un-changeable because of the plugin used to display the ratings: [jRate](https://github.com/senthilporunan/jRate).

**Comment by evertvp** [comment]
And there is no way of getting the actual value from the database and displaying it when hovering over the global score?

**Comment by tvgdb** [comment]
No. The API rounds the rating to the nearest 0.5 in-memory.
