### ISSUE TITLE
Global rating of tracks not visible

### ISSUE THREAD

**Issue by evertvp** [tvgdb/pianissimo#20]

**Comment by tvgdb** [comment]
The rating shown in tracks is always the global rating.

**Comment by evertvp** [comment]
Then the personal rating is not visible.

**Comment by tvgdb** [comment]
The personal rating was left out of the view because there is no space for it.

**Comment by evertvp** [comment]
The personal rating should be more important than the global one on that case, IMO.

Maybe the global one can be displayed as a simple number?

**Comment by tvgdb** [comment]
The personal rating could be shown in a tooltip when hovering over the global rating.

**Comment by evertvp** [comment]
If that is the only option I would prefer the personal rating to be shown by default and the global rating to be shown via tooltip.
