### ISSUE TITLE
Buttons overlap with player/play queue

### ISSUE THREAD

**Issue by evertvp** [tvgdb/pianissimo#23]
Buttons affected:
* Play collage
* Remove collage
* Play playlist
* Remove playlist
* Add to playlist
* Active checkboxes

**Comment by tvgdb** [comment]
Works here. Screenshot?

**Comment by evertvp** [comment]
![Screenshot](https://cloud.githubusercontent.com/assets/6755097/8376630/8f1157ec-1c09-11e5-86e6-420bf38d50b5.png)

**Comment by evertvp** [comment]
Active checkboxes still overlap with the player.

**Comment by tvgdb** [comment]
This is a known issue. The Materialize library uses this to animate the check-boxes.

I'll wait for Materialize to address this issue or provide a reasonable alternative.
