### ISSUE TITLE
Extensive tag support

### ISSUE THREAD

**Issue by fdema** [tvgdb/pianissimo#3]
Support for ID3v2 tags. Notably the composertag.

**Comment by evertvp** [comment]
Minimum supported tags should be: album, albumartist, artist, composer, genre, track, title, year.

**Comment by fdema** [comment]
Support for multiple performertags like conductor and orchestra would be nice.

**Comment by tvgdb** [comment]
Basic tag support implemented. Only these tags are supported: https://gist.github.com/tvgdb/cd19295cf2ae6a7882d9

Create a new issue for more tags.

**Comment by evertvp** [comment]
Not all tags listed here are implemented.

**Comment by tvgdb** [comment]
Fixed in d70c73a9921b19c06f00a859ac0bfc127f862a72
