### ISSUE TITLE
Group albums by albumartist if tag is available

### ISSUE THREAD

**Issue by evertvp** [tvgdb/pianissimo#6]

**Comment by fdema** [comment]
+ option to group album by composertag if available

**Comment by tvgdb** [comment]
Need some more explanation on this. What are the usecases?

**Comment by evertvp** [comment]
The albums by albumartist thing is already implemented AFAIK. (Maybe if the albumartist tag is not available, albums should attributed to the artist in the artist tag).

If I understand @fdema correctly, there should also be a composer view, where the albums these composers are on are listed.

**Comment by tvgdb** [comment]
The 'albumartist' tag is linked to the album and (should) be the same for all tracks in the album; therefore there is only 1 'albumartist' per album. 

The composer tag is *not* linked to the album, it can vary from track to track. Therefore an album doesn't necessary have only 1 'composer'-tag. You'd have to define a rule on how to pick the composer for that album (ex. composer of first track that has composer tag).

**Comment by evertvp** [comment]
If there is one track on an album with a specific composer, that album should be linked to that composer. So an album can be linked to multiple composers and a composer can be linked to multiple albums.
The composer view should then, for each composer, show the albums linked to that composer.

As for the albumartist, I agree. I just think that for libraries where the albumartist tag isn't consistently filled in, a link to the artist tag could be made (especially if the artist tag is the same for each track on the album). Right now those albums don't show up under the artist view, which isn't fully intuitive IMO.

**Comment by tvgdb** [comment]
So the composer(s) of an album are the composer(s) of all it's tracks?

And the 'albumartist' tag could be replaced by the 'artist' tag if the 'artist' tag is the same in all tracks of that album?

**Comment by evertvp** [comment]
Yeah, the composers of an album are the set of all the composers in the tracks of the album.

As for the albumartist, not replaced, but if there is no albumartist tag and all the artist tags are the same it seems logical to me that the artist tag can be viewed as an albumartist tag.

**Comment by tvgdb** [comment]
Just to be clear: do you want a page like the current albums page, but with the composers in stead of the albumartist; or do you want page like the current artists page, but with composers?

**Comment by evertvp** [comment]
Current artists but with composers
